/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-09-20 03:15:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/inc/top.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- content 영역 -->\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <main>\r\n");
      out.write("          <section class=\"py-5 text-center container\">\r\n");
      out.write("            <div class=\"row py-lg-5\">\r\n");
      out.write("              <div class=\"col-lg-6 col-md-8 mx-auto\">\r\n");
      out.write("                <h1 class=\"fw-light\">홈페이지 예제</h1>\r\n");
      out.write("                <p class=\"lead text-body-secondary\">Something short and\r\n");
      out.write("                  leading about the collection below—its contents, the creator,\r\n");
      out.write("                  etc. Make it short and sweet, but not too short so folks don’t\r\n");
      out.write("                  simply skip over it entirely.</p>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-primary my-2\">Main call to action</a>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary my-2\">Secondary action</a>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </section>\r\n");
      out.write("          <div class=\"album py-5 bg-body-tertiary\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("  \r\n");
      out.write("              <div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <image href=\"https://avatars.githubusercontent.com/u/36579880?v=4\" width=\"100%\" >\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <image href=\"https://avatars.githubusercontent.com/u/36579880?v=4\" width=\"100%\" ></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <image href=\"https://avatars.githubusercontent.com/u/36579880?v=4\" width=\"100%\" ></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("  \r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"card shadow-sm\">\r\n");
      out.write("                    <svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("                      height=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                      aria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("                      preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("                    <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                        fill=\"#55595c\" />\r\n");
      out.write("                    <text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("                        text below as a natural lead-in to additional content. This\r\n");
      out.write("                        content is a little bit longer.</p>\r\n");
      out.write("                      <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("                          <button type=\"button\"\r\n");
      out.write("                            class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-body-secondary\">9 mins</small>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("  \r\n");
      out.write("        </main>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- content 영역 끝 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
